
site_name: BUA Uppper Ontology
site_description: 'A docs test'
site_author: 'Rolf Guescini'
docs_dir: docs/
repo_name: 'BUA-VIVO/bua-upper-ontology'
repo_url: 'https://github.com/BUA-VIVO/bua-upper-ontology'
nav:
    - Home: index.md
theme:
  name: 'material'